### ISSUE TITLE
Как организовать тестирование кода, использующего ресурсы ОСРВ МАКС?

### ISSUE THREAD

**Issue by Alouettesu** [MIR-LLC/macs-rtos#4]
Задача: провести тестирование собственных классов, которые задействуют ресурсы ОСРВ МАКС. Соответственно, я запускаю эти тесты в контексте задачи. Однако как вернуть управление тестирующему фреймворку? Можете составить пример кода, который запускает некоторую функцию в контексте задачи, после чего происходит возврат управления?

**Comment by PavelLoktev** [comment]
Привет!

В ОСРВ МАКС нет механизма для завершения работы системы с возвратом в то место, откуда было запущено приложение (например, функция main).
Решить проблему можно обернув тестовый фреймворк в отдельную задачу. Ниже приведён пример возможного решения. 

////////////////////////////////////////////////////////////////

/*
* Одна из возможных реализаций.
* В main мы создаём и запускаем приложение ОС - выхода уже не будет.
* В приложении создаём задачу MainTask с повышенным приоритетом - она возьмёт на себя функции обычного main.
* Там можно создать сколько нужно задач с нормальным приоритетом - они пока не запускаются.
* Теперь понижаем приоритет MainTask - она останавливается.
* Когда все запущенные задачи завершатся - выполнение MainTask продолжится.
* Таким образом, в MainTask можно поместить код, который прежде был в функции main.
* Завершить приложение в обычном смысле с кодом возврата можно стандартной функцией exit() .
*/

static void Print(const char * msg1, const char * msg2) {
      printf("%s%s\n", msg1, msg2);
}

class TestTask : public Task
{
public:
      TestTask() : Task("Test") {}
      virtual void Execute();
};

void TestTask::Execute() {
      Print("In the ", GetName());
}


class MainTask : public Task
{
public:
      MainTask() : Task("Main") {}
      virtual void Execute();
};

void MainTask::Execute() {
      Print("Start the ", GetName());

      /*
      * Сюда помещаем код framework, в котором запускается тестирование. Сейчас для примера создание одной задачи.
      */
      Task::Add(new TestTask);

      SetPriority(Task::PriorityBelowNormal);

      /*
      * Сюда придём, когда завершатся все задачи с обычным приоритетом.
      */
      Print("End the ", GetName());

      /*
      * Здесь произойдёт выход из всего приложения.
      */
      exit(0);
}


class TestApp : public Application
{
private:
      virtual void Initialize();
};

void TestApp::Initialize() {
      Task::Add(new MainTask, Task::PriorityAboveNormal);
}

int main() {
      TestApp app;
      app.Run();
      return 0;
}
